site_name: FunEventSystems Root Documentation
nav:
    - 'Home' : 'index.md'
    - Lighting:
          - Modular Lights : modular-lights.md 
          - Lighting Board : lightboard.md
    - Tickets:
          - Ticket system : tickets.md
    - Management:
          - SideStage : team-manager.md
    - Video:
          - Vide0Stage: videoStage.md
    - Audio:
          - SoundStage: soundStage.md
    
    

theme:
  name: material


#plugins:
#    - with-pdf:
#        author: TheJades, GManAndMarbles
#        cover_title: Manual
#        cover_subtitle: V1.1
#        output_path: pdf/manual.pdf

        
