site_name: FunEventSystems Root Documentation
nav:
    - 'Home' : 'index.md'
    - ‘Lighting’:
          - ‘Modular Lights’ : ‘modular-lights.md’
          
    

theme:
  name: material


#plugins:
#    - with-pdf:
#        author: TheJades, GManAndMarbles
#        cover_title: Manual
#        cover_subtitle: V1.1
#        output_path: pdf/manual.pdf

        
